//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GroupPostAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.GroupPostDAO;
import dto.GroupPostDTO;


public class GroupPostAction {
	private GroupPostDAO groupPostDAO;
	public void setGroupPostDAO(GroupPostDAO groupPostDAO) {
		this.groupPostDAO = groupPostDAO;
	}
	
	public List<GroupPostDTO> getGroupPost() {
		return null;
	}
	
	public List<GroupPostDTO> getGroupPostById(String id) {
		List<GroupPostDTO> list = null;
		try{
			list = groupPostDAO.getGroupPostById(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public List<GroupPostDTO> getGroupPostByGroupNum(Integer groupNum) {
		List<GroupPostDTO> list = null;
		try{
			list = groupPostDAO.getGroupPostByGroupNum(groupNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public void deleteGroupPostByPostNum(Integer postNum) {
		try{
			groupPostDAO.deleteGroupPostByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteGroupPostByGroupNum(Integer groupNum) {
		try{
			groupPostDAO.deleteGroupPostByGroupNum(groupNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertGroupPost(int postNum, Integer groupNum) {
		try{
			groupPostDAO.insertGroupPost(postNum, groupNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
