//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ImageContentAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.ImageContentDAO;
import dto.ImageContentDTO;


public class ImageContentAction {
	private ImageContentDAO imageContentDAO;
	public void setImageContentDAO(ImageContentDAO imageContentDAO) {
		this.imageContentDAO = imageContentDAO;
	}
	
	public List<ImageContentDTO> getImageByNum(Integer imageNum) {
		return null;
	}
	
	public List<ImageContentDTO> getImage() {
		return null;
	}
	
	public List<ImageContentDTO> getImageByContentNum(Integer contentNum) {
		return null;
	}
	
	public List<ImageContentDTO> getImageByPostNum(Integer postNum) {
		List<ImageContentDTO> list = null;
		try{
			list = imageContentDAO.getImageByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public void updateImage(String image, Integer imageNum) {
		try{
			imageContentDAO.updateImage(image, imageNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteImage(Integer imageNum) {
		try{
			imageContentDAO.deleteImage(imageNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteImageByContentNum(Integer contentNum) {
	
	}
	
	public void deleteImageByPostNum(Integer postNum) {
		try{
			imageContentDAO.deleteImageByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertImage(String image, Integer postContentNum) {
		try{
			imageContentDAO.insertImage(image, postContentNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
