//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MyPagePostAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.MyPagePostDAO;
import dto.MyPagePostDTO;


public class MyPagePostAction {
	private MyPagePostDAO myPagePostDAO;
	public void setMyPagePostDAO(MyPagePostDAO myPagePostDAO) {
		this.myPagePostDAO = myPagePostDAO;
	}
	
	public List<MyPagePostDTO> getMyPagePost() {
		return null;
	}
	
	public List<MyPagePostDTO> getMyPagePostById(String id) {
		List<MyPagePostDTO> list = null;
		try{
			list = myPagePostDAO.getMyPagePostById(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public List<MyPagePostDTO> getMyPagePostByTitle(String title) {
		List<MyPagePostDTO> list = null;
		try{
			list = myPagePostDAO.getMyPagePostByTitle(title);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public void deleteMyPagePost(Integer postNum) {
		try{
			myPagePostDAO.deleteMyPagePost(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteMyPagePostByTitle(String myPageTitle) {
		try{
			myPagePostDAO.deleteMyPagePostByTitle(myPageTitle);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}	
	
	public void insertMyPagePost(Integer postNum, String myPageTitle) {
		try{
			myPagePostDAO.insertMyPagePost(postNum, myPageTitle);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
