//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PostTagUserAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.PostTagUserDAO;
import dto.PostTagUserDTO;


public class PostTagUserAction {
	private PostTagUserDAO postTagUserDAO;
	public void setPostTagUserDAO(PostTagUserDAO postTagUserDAO) {
		this.postTagUserDAO = postTagUserDAO;
	}
	
	public List<PostTagUserDTO> getPostTagUser() {
		return null;
	}
	
	public List<PostTagUserDTO> getPostTagUserByPostNum(Integer postNum) {
		List<PostTagUserDTO> list = null;
		try{
			list = postTagUserDAO.getPostTagUserByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public List<String> getTaggedId(Integer postNum) {
		List<String> list = null;
		try{
			list = postTagUserDAO.getTaggedId(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public PostTagUserDTO getPostTagUserByPostNumId(Integer postNum, String id) {
		PostTagUserDTO ptud = null;
		try{
			ptud = postTagUserDAO.getPostTagUserByPostNumId(postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return ptud;
	}
	
	public void deletePostTagUser(Integer postNum) {
		try{
			postTagUserDAO.deletePostTagUser(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deletePostTagUser(String id) {
		try{
			postTagUserDAO.deletePostTagUser(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertPostTagUser(Integer postNum, String id) {
		try{
			postTagUserDAO.insertPostTagUser(postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
