//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrivacyAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.PrivacyDAO;
import dto.PostTagUserDTO;
import dto.PrivacyDTO;


public class PrivacyAction {
	private PrivacyDAO privacyDAO;
	public void setPrivacyDAO(PrivacyDAO privacyDAO) {
		this.privacyDAO = privacyDAO;
	}
	
	public List<PrivacyDTO> getPrivacy() {
		return null;
	}
	
	public Integer getPrivacyLevel(String privacyContent) {
		Integer level = null;
		try{
			level = privacyDAO.getPrivacyLevel(privacyContent);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return level;
	}
	
	public String getPrivacyContent(Integer privacyLevel) {
		String content = null;
		try{
			 content = privacyDAO.getPrivacyContent(privacyLevel);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return content;
	}
	
	public void updatePrivacy(String privacyContent, Integer privacyLevel) {
		try{
			 privacyDAO.updatePrivacy(privacyContent, privacyLevel);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deletePrivacy(Integer privacyLevel) {
		try{
			 privacyDAO.deletePrivacy(privacyLevel);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deletePrivacyByContent(String privacyContent) {
		try{
			 privacyDAO.deletePrivacyByContent(privacyContent);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertPrivacy(Integer privacyLevel, String privacyContent) {
		try{
			 privacyDAO.insertPrivacy(privacyLevel, privacyContent);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
