//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecommendationKindAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.RecommendationKindDAO;
import dto.PostTagUserDTO;
import dto.RecommendationKindDTO;


public class RecommendationKindAction {
	private RecommendationKindDAO recommendationKindDAO;
	public void setRecommendationKindDAO(RecommendationKindDAO recommendationKindDAO) {
		this.recommendationKindDAO = recommendationKindDAO;
	}
	
	public List<RecommendationKindDTO> getRecommendationKind() {
		return null;
	}
	
	public RecommendationKindDTO getRecommendationKindByNum(Integer recommendationKindNum) {
		RecommendationKindDTO rd = null;
		try{
			rd =  recommendationKindDAO.getRecommendationKindByNum(recommendationKindNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return rd;
	}
	
	public void updateRecommendationKind(String recommendationKind, Integer recommendationKindNum) {
		try{
			 recommendationKindDAO.updateRecommendationKind(recommendationKind, recommendationKindNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteRecommendationKind(Integer recommendationKindNum) {
		try{
			 recommendationKindDAO.deleteRecommendationKind(recommendationKindNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertRecommendationKind(Integer recommendationKindNum, String recommendationKind) {
		try{
			 recommendationKindDAO.insertRecommendationKind(recommendationKindNum, recommendationKind);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
