//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecommendationUserAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.RecommendationUserDAO;
import dto.PostTagUserDTO;
import dto.RecommendationUserDTO;


public class RecommendationUserAction {
	private RecommendationUserDAO recommendationUserDAO;
	
	public void setRecommendationUserDAO(RecommendationUserDAO recommendationUserDAO) {
		this.recommendationUserDAO = recommendationUserDAO;
	}
	
	public List<RecommendationUserDTO> getRecommendationUser() {
		return null;
	}
	
	public List<RecommendationUserDTO> getRecommendationUserByPostNum(Integer postNum) {
		List<RecommendationUserDTO> list = null;
		try{
			list = recommendationUserDAO.getRecommendationUserByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public RecommendationUserDTO getRecommendationUserByRecoNum(Integer recommendationNum) {
		RecommendationUserDTO rud = null;
		try{
			recommendationUserDAO.getRecommendationUserByRecoNum(recommendationNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return rud;
	}
	
	public Integer getLikeBukkuCount(Integer postNum) {
		Integer count = null;
		try{
			recommendationUserDAO.getLikeBukkuCount(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public Integer getHateCount(Integer postNum) {
		Integer count = null;
		try{
			recommendationUserDAO.getHateCount(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public Integer updateRecommendationUser(Integer kind, Integer postNum, String id) {
		Integer count = null;
		try{
			recommendationUserDAO.updateRecommendationUser(kind, postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public void deleteRecommendationUserByPostNum(Integer postNum) {
		try{
			recommendationUserDAO.deleteRecommendationUserByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteRecommendationUserByRecoNum(Integer recommendationNum) {
		
	}
	
	public void deleteRecommendationUserById(String id) {
		try{
			recommendationUserDAO.deleteRecommendationUserById(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteRecommendationUserByPostNumId(Integer postNum, String id) {
		try{
			recommendationUserDAO.deleteRecommendationUserByPostNumId(postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertRecommendationUser(Integer recommendationKind, Integer postNum, String id) {
		try{
			recommendationUserDAO.insertRecommendationUser(recommendationKind, postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
