//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReportedUserAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.ReportedUserDAO;
import dto.RecommendationKindDTO;
import dto.ReportedUserDTO;


public class ReportedUserAction {
	private ReportedUserDAO reportedUserDAO;
	public void setReportedUserDAO(ReportedUserDAO reportedUserDAO) {
		this.reportedUserDAO = reportedUserDAO;
	}
	
	public List<ReportedUserDTO> getReportedUser() {
		List<ReportedUserDTO> list = null;
		try{
			list =  reportedUserDAO.getReportedUser();
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public ReportedUserDTO getReportedUserByReportNum(Integer reportNum) {
		ReportedUserDTO rud = null;
		try{
			rud = reportedUserDAO.getReportedUserByReportNum(reportNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return rud;
	}
	
	public List<ReportedUserDTO> getReportedUserByPostNum(Integer postNum) {
		List<ReportedUserDTO> list = null;
		try{
			list = reportedUserDAO.getReportedUserByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public List<ReportedUserDTO> getReportedUserByID(String id) {
		List<ReportedUserDTO> list = null;
		try{
			list = reportedUserDAO.getReportedUserByID(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public Integer getReportedUserCount(Integer postNum) {
		Integer count = null;
		try{
			count = reportedUserDAO.getReportedUserCount(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public void deleteReportedUserByPostNum(Integer postNum) {
		try{
			reportedUserDAO.deleteReportedUserByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteReportedUserByReportNum(Integer reportNum) {
		
	}
	
	public void deleteReportedUserByID(String id) {
		try{
			reportedUserDAO.deleteReportedUserByID(id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteReportedUserByIdPostNum(String id, Integer postNum) {
		try{
			reportedUserDAO.deleteReportedUserByIdPostNum(id, postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertReportedUser(Integer postNum, String id) {
		try{
			reportedUserDAO.insertReportedUser(postNum, id);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
