//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SharePostAction.java
//  @ Date : 2015-01-28
//  @ Author : 
//
//



package action;

import java.util.List;

import dao.DAOException;
import dao.SharePostDAO;
import dto.ReportedUserDTO;
import dto.SharePostDTO;


public class SharePostAction {
	private SharePostDAO sharePostDAO;
	public void setSharePostDAO(SharePostDAO sharePostDAO) {
		this.sharePostDAO = sharePostDAO;
	}
	
	public List<SharePostDTO> getSharePost() {
		return null;
	}
	
	public List<SharePostDTO> getSharePostByPostNum(Integer postNum) {
		List<SharePostDTO> list = null;
		try{
			list =  sharePostDAO.getSharePostByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public List<SharePostDTO> getSharePostByOriginPostNum(Integer originPostNum) {
		List<SharePostDTO> list = null;
		try{
			list =  sharePostDAO.getSharePostByOriginPostNum(originPostNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
		return list;
	}
	
	public void deleteSharePostByPostNum(Integer postNum) {
		try{
			sharePostDAO.deleteSharePostByPostNum(postNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void deleteSharePostByOriginPostNum(Integer originPostNum) {
		try{
			sharePostDAO.deleteSharePostByOriginPostNum(originPostNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
	
	public void insertSharePost(Integer postNum, Integer originPostNum) {
		try{
			sharePostDAO.insertSharePost(postNum, originPostNum);
		}catch(DAOException e){
			e.printStackTrace();
		}
	}
}
